DROP TABLE IF EXISTS "STOCK";

CREATE MEMORY TABLE "PUBLIC"."STOCK"(
    "ID" BIGINT NOT NULL,
    "LAST_PRICE" DECIMAL(19, 4),
    "NAME" VARCHAR(255),
    "TICKER_SYMBOL" VARCHAR(255),
    "STOCK_EXCHANGE" VARCHAR(255)
)